// 생성: 2026-10-06 16:07 KST

const CATEGORIES = ["한국사", "세계지리", "과학", "예술과 문화"];

const QUESTIONS = [
  // ----- 한국사 (history-01 ~ history-10) -----
  {
    id: "history-01",
    category: "한국사",
    question: "훈민정음을 창제한 조선의 임금은?",
    choices: ["세종", "태종", "세조", "성종"],
    answer: "세종",
    explanation: "세종은 글을 모르는 백성도 쓸 수 있도록 훈민정음을 직접 창제했다.",
    source: { name: "한국학중앙연구원 한국민족문화대백과사전 「훈민정음」", url: "https://encykorea.aks.ac.kr/Article/E0065805" },
  },
  {
    id: "history-02",
    category: "한국사",
    question: "궁예의 부하였다가 918년에 새 왕조를 열어 고려를 세운 인물은?",
    choices: ["왕건", "견훤", "신검", "양길"],
    answer: "왕건",
    explanation: "왕건은 918년 궁예를 내쫓고 새 왕조 고려의 태조가 되었다.",
    source: { name: "한국학중앙연구원 한국민족문화대백과사전 「태조」", url: "https://encykorea.aks.ac.kr/Article/E0059032" },
  },
  {
    id: "history-03",
    category: "한국사",
    question: "임진왜란 때 거북선을 만들어 해전에서 활약한 조선의 장수는?",
    choices: ["이순신", "권율", "김시민", "곽재우"],
    answer: "이순신",
    explanation: "이순신은 전투 장비를 정비하며 거북선을 만들었고, 임진왜란 해전에서 연이어 이겼다.",
    source: { name: "한국학중앙연구원 한국민족문화대백과사전 「거북선」", url: "https://encykorea.aks.ac.kr/Article/E0001833" },
  },
  {
    id: "history-04",
    category: "한국사",
    question: "건국 신화에 따르면 고구려를 세운 제1대 왕의 이름은?",
    choices: ["주몽", "온조", "혁거세", "수로"],
    answer: "주몽",
    explanation: "고구려 제1대 왕 동명성왕의 이름은 주몽 또는 추모로 전한다.",
    source: { name: "한국학중앙연구원 한국민족문화대백과사전 「동명성왕」", url: "https://encykorea.aks.ac.kr/Article/E0016431" },
  },
  {
    id: "history-05",
    category: "한국사",
    question: "인도의 불교 유적을 순례하고 『왕오천축국전』을 남긴 신라 승려는?",
    choices: ["혜초", "원효", "의상", "자장"],
    answer: "혜초",
    explanation: "『왕오천축국전』은 통일신라 승려 혜초가 오천축국의 불교 유적을 순례한 기록이다.",
    source: { name: "한국학중앙연구원 한국민족문화대백과사전 「왕오천축국전」", url: "https://encykorea.aks.ac.kr/Article/E0039126" },
  },
  {
    id: "history-06",
    category: "한국사",
    question: "조선 정조가 아버지 사도세자의 무덤을 옮긴 고을에 새로 쌓은 성곽은?",
    choices: ["수원 화성", "공주 공산성", "광주 남한산성", "고양 행주산성"],
    answer: "수원 화성",
    explanation: "정조는 사도세자의 무덤을 수원으로 옮긴 뒤 화성을 쌓아 1796년에 완성했다.",
    source: { name: "한국학중앙연구원 한국민족문화대백과사전 「수원 화성」", url: "https://encykorea.aks.ac.kr/Article/E0064671" },
  },
  {
    id: "history-07",
    category: "한국사",
    question: "거족적인 독립만세운동인 3·1운동이 일어난 해는?",
    choices: ["1919년", "1910년", "1926년", "1929년"],
    answer: "1919년",
    explanation: "3·1운동은 1919년 3월 1일을 기해 일어난 거족적인 독립만세운동이다.",
    source: { name: "한국학중앙연구원 한국민족문화대백과사전 「3·1운동」", url: "https://encykorea.aks.ac.kr/Article/E0026772" },
  },
  {
    id: "history-08",
    category: "한국사",
    question: "몽골 침입으로 초조대장경이 불탄 뒤 고려가 다시 새긴 대장경판을 보관한 사찰은?",
    choices: ["해인사", "불국사", "통도사", "송광사"],
    answer: "해인사",
    explanation: "고려가 대장도감을 두어 1251년에 완성한 대장경판은 합천 해인사에 소장되어 있다.",
    source: { name: "한국학중앙연구원 한국민족문화대백과사전 「해인사 대장경」", url: "https://encykorea.aks.ac.kr/Article/E0062710" },
  },
  {
    id: "history-09",
    category: "한국사",
    question: "수령이 지켜야 할 책무와 통치 기술을 담은 『목민심서』를 지은 조선 후기 실학자는?",
    choices: ["정약용", "박지원", "박제가", "유형원"],
    answer: "정약용",
    explanation: "『목민심서』는 실학자 정약용이 수령의 책무와 지방 통치 이념을 담은 책이다.",
    source: { name: "한국학중앙연구원 한국민족문화대백과사전 「목민심서」", url: "https://encykorea.aks.ac.kr/Article/E0018631" },
  },
  {
    id: "history-10",
    category: "한국사",
    question: "1919년 4월에 대한민국 임시정부가 처음 수립된 도시는?",
    choices: ["상하이", "베이징", "난징", "충칭"],
    answer: "상하이",
    explanation: "임시정부는 1919년 4월 상하이에 수립되었고, 여러 곳을 옮겨 다니다 1940년 충칭에 자리 잡았다.",
    source: { name: "한국학중앙연구원 한국민족문화대백과사전 「대한민국 임시정부」", url: "https://encykorea.aks.ac.kr/Article/E0015017" },
  },

  // ----- 세계지리 (geography-01 ~ geography-10) -----
  {
    id: "geography-01",
    category: "세계지리",
    question: "오스트레일리아의 수도는?",
    choices: ["캔버라", "시드니", "멜버른", "퍼스"],
    answer: "캔버라",
    explanation: "오스트레일리아의 수도는 시드니가 아니라 캔버라이다.",
    source: { name: "한국학중앙연구원 한국민족문화대백과사전 「오스트레일리아」", url: "https://encykorea.aks.ac.kr/Article/E0038381" },
  },
  {
    id: "geography-02",
    category: "세계지리",
    question: "캐나다의 수도는?",
    choices: ["오타와", "토론토", "밴쿠버", "몬트리올"],
    answer: "오타와",
    explanation: "캐나다의 수도는 오타와이며, 토론토와 밴쿠버는 수도가 아니다.",
    source: { name: "한국학중앙연구원 한국민족문화대백과사전 「캐나다」", url: "https://encykorea.aks.ac.kr/Article/E0058615" },
  },
  {
    id: "geography-03",
    category: "세계지리",
    question: "튀르키예의 수도는?",
    choices: ["앙카라", "이스탄불", "이즈미르", "안탈리아"],
    answer: "앙카라",
    explanation: "튀르키예의 수도는 이스탄불이 아니라 앙카라이다.",
    source: { name: "한국학중앙연구원 한국민족문화대백과사전 「튀르키예」", url: "https://encykorea.aks.ac.kr/Article/E0059145" },
  },
  {
    id: "geography-04",
    category: "세계지리",
    question: "남아메리카 서북부에 있는 에콰도르의 수도는?",
    choices: ["키토", "리마", "보고타", "라파스"],
    answer: "키토",
    explanation: "남아메리카 서북부의 공화국 에콰도르의 수도는 키토이다.",
    source: { name: "한국학중앙연구원 한국민족문화대백과사전 「에콰도르」", url: "https://encykorea.aks.ac.kr/Article/E0036268" },
  },
  {
    id: "geography-05",
    category: "세계지리",
    question: "스칸디나비아반도 북서부에 있는 노르웨이의 수도는?",
    choices: ["오슬로", "헬싱키", "코펜하겐", "스톡홀름"],
    answer: "오슬로",
    explanation: "스칸디나비아반도 북서부의 입헌군주국 노르웨이의 수도는 오슬로이다.",
    source: { name: "한국학중앙연구원 한국민족문화대백과사전 「노르웨이」", url: "https://encykorea.aks.ac.kr/Article/E0012729" },
  },
  {
    id: "geography-06",
    category: "세계지리",
    question: "브라질의 공용어는?",
    choices: ["포르투갈어", "스페인어", "프랑스어", "이탈리아어"],
    answer: "포르투갈어",
    explanation: "브라질의 공용어는 스페인어가 아니라 포르투갈어이다.",
    source: { name: "한국학중앙연구원 한국민족문화대백과사전 「브라질」", url: "https://encykorea.aks.ac.kr/Article/E0025067" },
  },
  {
    id: "geography-07",
    category: "세계지리",
    question: "눈 덮인 화산인 킬리만자로산이 있는 아프리카 나라는?",
    choices: ["탄자니아", "케냐", "우간다", "르완다"],
    answer: "탄자니아",
    explanation: "킬리만자로산은 탄자니아에 있는 눈 덮인 화산이다.",
    source: { name: "National Geographic Education 「Kilimanjaro」", url: "https://education.nationalgeographic.org/resource/kilimanjaro/" },
  },
  {
    id: "geography-08",
    category: "세계지리",
    question: "아프리카 북동부를 남에서 북으로 흘러 이집트 해안에서 지중해로 들어가는 강은?",
    choices: ["나일강", "콩고강", "니제르강", "잠베지강"],
    answer: "나일강",
    explanation: "나일강은 아프리카 북동부를 남에서 북으로 흘러 이집트 해안에서 지중해로 들어간다.",
    source: { name: "National Geographic Education 「Nile River」", url: "https://education.nationalgeographic.org/resource/nile-river/" },
  },
  {
    id: "geography-09",
    category: "세계지리",
    question: "남아메리카 대륙의 서쪽 끝을 따라 남북으로 길게 뻗은 산맥은?",
    choices: ["안데스산맥", "로키산맥", "알프스산맥", "아틀라스산맥"],
    answer: "안데스산맥",
    explanation: "안데스산맥은 남아메리카 서쪽 끝에서 대륙 남단부터 북쪽 해안까지 뻗어 있다.",
    source: { name: "National Geographic Education 「South America: Physical Geography」", url: "https://education.nationalgeographic.org/resource/south-america-physical-geography/" },
  },
  {
    id: "geography-10",
    category: "세계지리",
    question: "2024년 기준, 면적으로 따져서 가장 넓은 나라는?",
    choices: ["러시아", "캐나다", "중국", "미국"],
    answer: "러시아",
    explanation: "캐나다는 면적이 러시아에 이어 세계 2위이므로, 면적 1위는 러시아이다.",
    source: { name: "한국학중앙연구원 한국민족문화대백과사전 「캐나다」", url: "https://encykorea.aks.ac.kr/Article/E0058615" },
  },

  // ----- 과학 (science-01 ~ science-10) -----
  {
    id: "science-01",
    category: "과학",
    question: "태양과의 거리를 기준으로 할 때 태양에 가장 가까운 행성은?",
    choices: ["수성", "금성", "화성", "지구"],
    answer: "수성",
    explanation: "수성은 태양계에서 가장 작은 행성이며 태양에 가장 가깝다.",
    source: { name: "NASA Science 「Mercury: Facts」", url: "https://science.nasa.gov/mercury/facts/" },
  },
  {
    id: "science-02",
    category: "과학",
    question: "흙 속의 철 광물이 녹슬어 표면이 붉게 보이는 '붉은 행성'은?",
    choices: ["화성", "목성", "금성", "토성"],
    answer: "화성",
    explanation: "화성은 흙과 먼지 속 철 광물이 산화되어(녹슬어) 표면이 붉게 보인다.",
    source: { name: "NASA Science 「Mars: Facts」", url: "https://science.nasa.gov/mars/facts/" },
  },
  {
    id: "science-03",
    category: "과학",
    question: "크기를 기준으로 할 때 태양계에서 가장 큰 행성은?",
    choices: ["목성", "토성", "천왕성", "해왕성"],
    answer: "목성",
    explanation: "목성은 태양계에서 가장 큰 행성이다.",
    source: { name: "NASA Science 「Jupiter: Facts」", url: "https://science.nasa.gov/jupiter/facts/" },
  },
  {
    id: "science-04",
    category: "과학",
    question: "1969년 아폴로 11호 임무에서 처음으로 달에 발을 디딘 사람은?",
    choices: ["닐 암스트롱", "버즈 올드린", "마이클 콜린스", "유리 가가린"],
    answer: "닐 암스트롱",
    explanation: "아폴로 11호 승무원 암스트롱, 콜린스, 올드린 가운데 암스트롱이 처음 달에 발을 디뎠다.",
    source: { name: "NASA 「Apollo 11」", url: "https://www.nasa.gov/mission/apollo-11/" },
  },
  {
    id: "science-05",
    category: "과학",
    question: "주기율표에서 원자 번호가 1인 원소는?",
    choices: ["수소", "헬륨", "리튬", "탄소"],
    answer: "수소",
    explanation: "원자 번호 1번 원소는 원소 기호 H로 쓰는 수소이다.",
    source: { name: "미국 국립보건원 PubChem 「Hydrogen」", url: "https://pubchem.ncbi.nlm.nih.gov/element/1" },
  },
  {
    id: "science-06",
    category: "과학",
    question: "적혈구 속에서 산소를 운반하는 단백질은?",
    choices: ["헤모글로빈", "피브리노겐", "알부민", "케라틴"],
    answer: "헤모글로빈",
    explanation: "헤모글로빈은 적혈구에 들어 있는 단백질로, 산소를 운반한다.",
    source: { name: "미국 국립의학도서관 MedlinePlus 「Hemoglobin」", url: "https://medlineplus.gov/ency/article/003645.htm" },
  },
  {
    id: "science-07",
    category: "과학",
    question: "고체에서 곧바로 기체로 상태가 바뀌는 현상은?",
    choices: ["승화", "융해", "응결", "기화"],
    answer: "승화",
    explanation: "승화는 액체 단계 없이 고체와 기체 사이에서 상태가 바뀌는 현상이다.",
    source: { name: "미국 지질조사국(USGS) 「Sublimation and the Water Cycle」", url: "https://www.usgs.gov/water-science-school/science/sublimation-and-water-cycle" },
  },
  {
    id: "science-08",
    category: "과학",
    question: "19세기에 완두 교배 실험으로 유전의 기본 법칙을 밝힌 사람은?",
    choices: ["멘델", "다윈", "뉴턴", "돌턴"],
    answer: "멘델",
    explanation: "오스트리아의 수도사 멘델은 완두 실험으로 유전의 기본 법칙을 밝혔다.",
    source: { name: "미국 국립인간게놈연구소 「Mendel, Johann (Gregor)」", url: "https://www.genome.gov/genetics-glossary/Gregor-Johann-Mendel" },
  },
  {
    id: "science-09",
    category: "과학",
    question: "지표 부근 공기를 기준으로 할 때 지구 대기에 가장 많은 기체는?",
    choices: ["질소", "산소", "아르곤", "네온"],
    answer: "질소",
    explanation: "지표 부근의 지구 대기는 질소 78%, 산소 21%, 그 밖의 기체 1%로 이루어져 있다.",
    source: { name: "NASA Science 「Earth: Facts」", url: "https://science.nasa.gov/earth/facts/" },
  },
  {
    id: "science-10",
    category: "과학",
    question: "식물 세포 안에서 햇빛 에너지를 저장해 광합성을 하는 작은 기관은?",
    choices: ["엽록체", "액포", "골지체", "리보솜"],
    answer: "엽록체",
    explanation: "식물 세포 안의 작은 기관인 엽록체가 햇빛 에너지를 저장해 광합성을 한다.",
    source: { name: "National Geographic Education 「Photosynthesis」", url: "https://education.nationalgeographic.org/resource/photosynthesis/" },
  },

  // ----- 예술과 문화 (arts-01 ~ arts-10) -----
  {
    id: "arts-01",
    category: "예술과 문화",
    question: "안평대군의 꿈 이야기를 듣고 「몽유도원도」를 그린 조선 초기 화가는?",
    choices: ["안견", "정선", "김홍도", "신윤복"],
    answer: "안견",
    explanation: "「몽유도원도」는 안평대군이 꿈에 본 도원을 설명하자 안견이 그린 산수화이다.",
    source: { name: "한국학중앙연구원 한국민족문화대백과사전 「몽유도원도」", url: "https://encykorea.aks.ac.kr/Article/E0018824" },
  },
  {
    id: "arts-02",
    category: "예술과 문화",
    question: "비 온 뒤의 인왕산 경치를 그린 「인왕제색도」의 화가는?",
    choices: ["정선", "안견", "김홍도", "장승업"],
    answer: "정선",
    explanation: "「인왕제색도」는 조선 후기 화가 정선이 비 온 뒤의 인왕산 경치를 보고 그린 산수화이다.",
    source: { name: "한국학중앙연구원 한국민족문화대백과사전 「정선 필 인왕제색도」", url: "https://encykorea.aks.ac.kr/Article/E0046984" },
  },
  {
    id: "arts-03",
    category: "예술과 문화",
    question: "「서당」과 「씨름」이 들어 있는 조선 후기 풍속도 화첩을 그린 화가는?",
    choices: ["김홍도", "신윤복", "정선", "안견"],
    answer: "김홍도",
    explanation: "김홍도가 그린 『풍속도 화첩』에서 뛰어난 장면으로 「서당」과 「씨름」을 꼽는다.",
    source: { name: "한국학중앙연구원 한국민족문화대백과사전 「김홍도 필 풍속도 화첩」", url: "https://encykorea.aks.ac.kr/Article/E0013639" },
  },
  {
    id: "arts-04",
    category: "예술과 문화",
    question: "판소리에서 북을 치며 장단을 맞추고 추임새로 소리판을 이끄는 사람은?",
    choices: ["고수", "광대", "재인", "무동"],
    answer: "고수",
    explanation: "고수는 북을 치는 음악인으로, 판소리에서 장단을 맞추고 추임새로 분위기를 이끈다.",
    source: { name: "한국학중앙연구원 한국민족문화대백과사전 「고수」", url: "https://encykorea.aks.ac.kr/Article/E0003767" },
  },
  {
    id: "arts-05",
    category: "예술과 문화",
    question: "고려 사람들이 '비색'이라 부른, 회색 바탕에 녹청색을 띠는 자기는?",
    choices: ["청자", "백자", "흑자", "분청"],
    answer: "청자",
    explanation: "청자는 회색 바탕의 녹청색을 띠며, 고려 사람들은 이 색을 비색이라 했다.",
    source: { name: "한국학중앙연구원 한국민족문화대백과사전 「청자」", url: "https://encykorea.aks.ac.kr/Article/E0056611" },
  },
  {
    id: "arts-06",
    category: "예술과 문화",
    question: "1922년 『개벽』에 처음 발표된 시 「진달래꽃」을 쓴 시인은?",
    choices: ["김소월", "윤동주", "한용운", "이육사"],
    answer: "김소월",
    explanation: "「진달래꽃」은 1922년 7월 『개벽』에 처음 발표한 김소월의 시이다.",
    source: { name: "한국학중앙연구원 한국민족문화대백과사전 「진달래꽃」", url: "https://encykorea.aks.ac.kr/Article/E0054623" },
  },
  {
    id: "arts-07",
    category: "예술과 문화",
    question: "승려 성진이 양소유로 태어나 부귀공명을 누리는 꿈을 꾸는 소설 「구운몽」의 지은이는?",
    choices: ["김만중", "허균", "박지원", "김시습"],
    answer: "김만중",
    explanation: "「구운몽」은 조선 숙종 때 김만중이 지은 고전 소설이다.",
    source: { name: "한국학중앙연구원 한국민족문화대백과사전 「구운몽」", url: "https://encykorea.aks.ac.kr/Article/E0005948" },
  },
  {
    id: "arts-08",
    category: "예술과 문화",
    question: "오동나무 공명판 위에 명주실로 꼰 열두 줄을 걸어 연주하는 전통 현악기는?",
    choices: ["가야금", "거문고", "해금", "아쟁"],
    answer: "가야금",
    explanation: "가야금은 오동나무 공명판에 명주실로 꼰 12줄을 걸고, 줄을 뜯고 퉁겨 연주한다.",
    source: { name: "한국학중앙연구원 한국민족문화대백과사전 「가야금」", url: "https://encykorea.aks.ac.kr/Article/E0000261" },
  },
  {
    id: "arts-09",
    category: "예술과 문화",
    question: "프랑스 루브르 박물관이 소장한 초상화 「모나리자」를 그린 화가는?",
    choices: ["다빈치", "미켈란젤로", "라파엘로", "보티첼리"],
    answer: "다빈치",
    explanation: "루브르 박물관의 「모나리자」(라 조콘드)는 레오나르도 다빈치가 그린 초상화이다.",
    source: { name: "루브르 박물관 「La Joconde」", url: "https://collections.louvre.fr/en/ark:/53355/cl010062370" },
  },
  {
    id: "arts-10",
    category: "예술과 문화",
    question: "덴마크 왕자가 아버지를 죽인 숙부에게 복수하려는 비극 「햄릿」을 쓴 작가는?",
    choices: ["셰익스피어", "세르반테스", "몰리에르", "체호프"],
    answer: "셰익스피어",
    explanation: "「햄릿」은 셰익스피어의 복수 비극으로, 햄릿이 아버지를 죽인 숙부 클로디어스에게 복수하려 한다.",
    source: { name: "폴저 셰익스피어 도서관 「Hamlet」", url: "https://www.folger.edu/explore/shakespeares-works/hamlet/" },
  },
];
